apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-db
  template:
    metadata:
      labels:
        app: redis-db
    spec:
      containers:
      - image: redis
        name: redis-db
        ports:
        - containerPort: 6379
